/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_TestJni */

#ifndef _Included_test_TestJni
#define _Included_test_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_TestJni
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_TestJni_getName
  (JNIEnv *, jclass);

/*
 * Class:     test_TestJni
 * Method:    main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_test_TestJni_main
  (JNIEnv *, jclass);

/*
 * Class:     test_TestJni
 * Method:    initVM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_test_TestJni_initVM
  (JNIEnv *, jclass);

/*
 * Class:     test_TestJni
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_TestJni_run
  (JNIEnv *, jclass);

/*
 * Class:     test_TestJni
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_TestJni_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
